services:
  db:
    image: mysql:5.7
    container_name: phportfolio_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: phportfolio
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 2
    ports:
      - "3306:3306"

  db-init:
    image: mysql:5.7                                     
    depends_on:
      db:
        condition: service_healthy                      
    volumes:
      - ./application/config:/init-scripts:ro
    environment:
      - SEEDS
    entrypoint: >
      sh -c "
        mysql -h db -uuser -ppassword phportfolio < /init-scripts/init_db.sql &&
        if [ \"${SEEDS}\" = \"true\" ]; then
          echo '[seed] Exécution de seed_db.sql' &&
          mysql -h db -uuser -ppassword phportfolio < /init-scripts/seed_db.sql;
        else
          echo '[seed] Ignoré (SEEDS='\"${SEEDS}\"')';
        fi
      "
    restart: "no"

  web:
    build: .
    container_name: phportfolio_web
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
    depends_on:
      - db-init

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phportfolio_pma
    depends_on:
      - db-init
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db

volumes:
  dbdata:
    driver: local
